service: ${env:APP_NAME}
frameworkVersion: '2'
variablesResolutionMode: 20210326
configValidationMode: warn
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  stackName: ${self:service}
  stage: ${env:STAGE}
  region: ${env:AWS_REGION, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - s3:*
            - kms:Describe*
            - kms:Encrypt*
            - kms:Decrypt*
            - kms:GenerateDataKey
          Resource: '*'
        - Effect: Allow
          Action:
            - ssm:GetParametersByPath
          Resource:
            - arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter${self:provider.environment.SSM_APP_PATH}
  logRetentionInDays: 30
  environment: ${self:custom.environment.${self:provider.stage}}

custom:
  defaultEnvVars: &defaultEnvVars
    STAGE: ${self:provider.stage}
    SSM_APP_PATH: /app/${stage}/${self:service}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
  environment:
    prod:
      <<: *defaultEnvVars
      AWS_DYNAMODB_TABLE:
        Ref: Table
    local:
      <<: *defaultEnvVars
      AWS_DYNAMODB_ENDPOINT: http://localhost:4566
      AWS_DYNAMODB_TABLE: ${self:service}
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9777
    noPrependStageInUrl: true
  webpack:
    webpackConfig: ./webpack.config.js
    packager: npm
    includeModules: true
  prune:
    automatic: true
    includeLayers: true
    number: 5

functions:
  api:
    handler: src/index.api
    events:
      - httpApi: '*'

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        Tags:
          - Key: Name
            Value: ${self:service}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        SSESpecification:
          SSEEnabled: true
          SSEType: KMS
        # PointInTimeRecoverySpecification:
        #   PointInTimeRecoveryEnabled: true

    WriteCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      Properties:
        MaxCapacity: 100
        MinCapacity: 1
        ResourceId:
          Fn::Join:
            - /
            - - table
              - !Ref Table
        RoleARN:
          Fn::GetAtt:
            - ScalingRole
            - Arn
        ScalableDimension: dynamodb:table:WriteCapacityUnits
        ServiceNamespace: dynamodb

    ReadCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      Properties:
        MaxCapacity: 100
        MinCapacity: 1
        ResourceId:
          Fn::Join:
            - /
            - - table
              - !Ref Table
        RoleARN:
          Fn::GetAtt:
            - ScalingRole
            - Arn
        ScalableDimension: dynamodb:table:ReadCapacityUnits
        ServiceNamespace: dynamodb

    ScalingRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - application-autoscaling.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: '/'
        Policies:
          -
            PolicyName:
              Fn::Join:
                - '-'
                - - !Ref Table
                  - scaling-role
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - dynamodb:DescribeTable
                    - dynamodb:UpdateTable
                    - cloudwatch:PutMetricAlarm
                    - cloudwatch:DescribeAlarms
                    - cloudwatch:GetMetricStatistics
                    - cloudwatch:SetAlarmState
                    - cloudwatch:DeleteAlarms
                  Resource: '*'

    WriteScalingPolicy:
      Type: AWS::ApplicationAutoScaling::ScalingPolicy
      Properties:
        PolicyName: WriteAutoScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId:
          Ref: WriteCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
          TargetValue: 30.0
          ScaleInCooldown: 60
          ScaleOutCooldown: 60
          PredefinedMetricSpecification:
            PredefinedMetricType: DynamoDBWriteCapacityUtilization

    ReadScalingPolicy:
      Type: AWS::ApplicationAutoScaling::ScalingPolicy
      Properties:
        PolicyName: ReadutoScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId:
          Ref: ReadCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
          TargetValue: 30.0
          ScaleInCooldown: 60
          ScaleOutCooldown: 60
          PredefinedMetricSpecification:
            PredefinedMetricType: DynamoDBReadCapacityUtilization

    CustomDomain:
      Type: AWS::ApiGatewayV2::DomainName
      Properties: 
        DomainName: ${env:ROUTE53_RECORD_NAME}
        DomainNameConfigurations: 
          - CertificateArn: ${env:ACM_CERTIFICATE_ARN}
            SecurityPolicy: TLS_1_2
            EndpointType: REGIONAL

    ApiMapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Properties: 
        ApiId:
          Ref: HttpApi
        DomainName:
          Ref: CustomDomain
        Stage:
          Ref: HttpApiStage

    DnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        AliasTarget:
          DNSName:
            Fn::GetAtt:
              - CustomDomain
              - RegionalDomainName
          HostedZoneId:
            Fn::GetAtt:
              - CustomDomain
              - RegionalHostedZoneId
          EvaluateTargetHealth: false
        HostedZoneId: ${env:ROUTE53_HOSTED_ZONE_ID}
        Name: ${env:ROUTE53_RECORD_NAME}.
        Type: A
